CREATE TABLE `traveling`.`visa_price_for_package` (`id` INT NOT NULL AUTO_INCREMENT, `visa_id` INT NULL  , `adult_buying` VARCHAR(255) NULL ,`adult_selling` VARCHAR(255) NULL , `child_buying` VARCHAR(255) NULL ,`child_selling` VARCHAR(255) NULL , `infant_buying` VARCHAR(255) NULL ,`infant_selling` VARCHAR(255) NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `traveling`.`visa_price_for_individual` (`id` INT NOT NULL AUTO_INCREMENT, `visa_id` INT NULL  , `adult_buying` VARCHAR(255) NULL ,`adult_selling` VARCHAR(255) NULL , `child_buying` VARCHAR(255) NULL ,`child_selling` VARCHAR(255) NULL , `infant_buying` VARCHAR(255) NULL ,`infant_selling` VARCHAR(255) NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `traveling`.`lodging_service` (`id` INT NOT NULL AUTO_INCREMENT, `hotel_name` VARCHAR(255) NULL  , `city` VARCHAR(255) NULL ,`hotel_type` VARCHAR(255) NULL , `available_from` VARCHAR(255) NULL ,`available_to` VARCHAR(255) NULL , `rooms_for_two` VARCHAR(255) NULL ,`rooms_for_three` VARCHAR(255) NULL,`rooms_for_four` VARCHAR(255) NULL ,`rooms_for_five` VARCHAR(255) NULL, `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `traveling`.`lodging_service_price_for_package` (`id` INT NOT NULL AUTO_INCREMENT, `hotel_id` INT NULL  , `room_two_buying_adult` VARCHAR(255) NULL , `room_two_selling_adult` VARCHAR(255) NULL , `room_two_buying_child` VARCHAR(255) NULL , `room_two_selling_child` VARCHAR(255) NULL  , `room_two_buying_infant` VARCHAR(255) NULL , `room_two_selling_infant` VARCHAR(255) NULL , `room_three_buying_adult` VARCHAR(255) NULL , `room_three_selling_adult` VARCHAR(255) NULL , `room_three_buying_child` VARCHAR(255) NULL , `room_three_selling_child` VARCHAR(255) NULL  , `room_three_buying_infant` VARCHAR(255) NULL , `room_three_selling_infant` VARCHAR(255) NULL , `room_four_buying_adult` VARCHAR(255) NULL , `room_four_selling_adult` VARCHAR(255) NULL , `room_four_buying_child` VARCHAR(255) NULL , `room_four_selling_child` VARCHAR(255) NULL  , `room_four_buying_infant` VARCHAR(255) NULL , `room_four_selling_infant` VARCHAR(255) NULL , `room_five_buying_adult` VARCHAR(255) NULL , `room_five_selling_adult` VARCHAR(255) NULL , `room_five_buying_child` VARCHAR(255) NULL , `room_five_selling_child` VARCHAR(255) NULL  , `room_five_buying_infant` VARCHAR(255) NULL , `room_five_selling_infant` VARCHAR(255) NULL, `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `traveling`.`lodging_service_price_for_individual` (`id` INT NOT NULL AUTO_INCREMENT, `hotel_id` INT NULL  , `room_two_buying_adult` VARCHAR(255) NULL , `room_two_selling_adult` VARCHAR(255) NULL , `room_two_buying_child` VARCHAR(255) NULL , `room_two_selling_child` VARCHAR(255) NULL  , `room_two_buying_infant` VARCHAR(255) NULL , `room_two_selling_infant` VARCHAR(255) NULL , `room_three_buying_adult` VARCHAR(255) NULL , `room_three_selling_adult` VARCHAR(255) NULL , `room_three_buying_child` VARCHAR(255) NULL , `room_three_selling_child` VARCHAR(255) NULL  , `room_three_buying_infant` VARCHAR(255) NULL , `room_three_selling_infant` VARCHAR(255) NULL , `room_four_buying_adult` VARCHAR(255) NULL , `room_four_selling_adult` VARCHAR(255) NULL , `room_four_buying_child` VARCHAR(255) NULL , `room_four_selling_child` VARCHAR(255) NULL  , `room_four_buying_infant` VARCHAR(255) NULL , `room_four_selling_infant` VARCHAR(255) NULL , `room_five_buying_adult` VARCHAR(255) NULL , `room_five_selling_adult` VARCHAR(255) NULL , `room_five_buying_child` VARCHAR(255) NULL , `room_five_selling_child` VARCHAR(255) NULL  , `room_five_buying_infant` VARCHAR(255) NULL , `room_five_selling_infant` VARCHAR(255) NULL, `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `traveling`.`ticket_service` (`id` INT NOT NULL AUTO_INCREMENT, `name` VARCHAR(255) NULL  , `type` VARCHAR(255) NULL ,`flight_type` VARCHAR(255) NULL , `air_company` VARCHAR(255) NULL ,`buying_price_for_package` VARCHAR(255) NULL , `selling_price_for_package` VARCHAR(255) NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `traveling`.`transport_service` (`id` INT NOT NULL AUTO_INCREMENT, `name` VARCHAR(255) NULL  , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `traveling`.`reservation` (`id` INT NOT NULL AUTO_INCREMENT, `customer_id` INT NULL  , `service_type` VARCHAR(255) NULL  , `reservation_status` VARCHAR(255) NULL, `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;


CREATE TABLE `traveling`.`package_reservation` (`id` INT NOT NULL AUTO_INCREMENT, `reservation_id` INT  NULL, `package_type` VARCHAR(255) NULL ,`name` VARCHAR(255) NULL , `from_date` VARCHAR(255) NULL ,`to_date` VARCHAR(255) NULL , `length_of_stay` VARCHAR(255) NULL ,`service_price` VARCHAR(255) NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `traveling`.`lodging_reservation` (`id` INT NOT NULL AUTO_INCREMENT, `reservation_id` INT NULL  , `destination` VARCHAR(255) NULL ,`lodging_in_madina` VARCHAR(255) NULL , `room_type_in_madina` VARCHAR(255) NULL, `from_date_madina` VARCHAR(255) NULL ,`to_date_madina` VARCHAR(255) NULL  ,`lodging_in_makkah` VARCHAR(255) NULL , `room_type_in_makkah` VARCHAR(255) NULL, `from_date_makkah` VARCHAR(255) NULL ,`to_date_makkah` VARCHAR(255) NULL , `length_of_stay` VARCHAR(255) NULL ,`madina_price` VARCHAR(255) NULL ,`makkah_price` VARCHAR(255) NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `traveling`.`visa_reservation` (`id` INT NOT NULL AUTO_INCREMENT, `reservation_id` INT NULL  , `visa_type` VARCHAR(255) NULL , `from_date` VARCHAR(255) NULL ,`to_date` VARCHAR(255) NULL , `length_of_stay` VARCHAR(255) NULL ,`service_price` VARCHAR(255) NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `traveling`.`flight_reservation` (`id` INT NOT NULL AUTO_INCREMENT, `reservation_id` INT NULL  , `flight_id` VARCHAR(255) NULL , `from_airport` VARCHAR(255) NULL ,`to_airport` VARCHAR(255) NULL , `trip_type` VARCHAR(255) NULL , `flight_type` VARCHAR(255) NULL , `airline_id` VARCHAR(255) NULL ,`departure_time` VARCHAR(255) NULL ,`return_time` VARCHAR(255) NULL , `service_price` VARCHAR(255) NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `traveling`.`transport_reservation` (`id` INT NOT NULL AUTO_INCREMENT, `reservation_id` INT NULL  , `country` VARCHAR(255) NULL , `type` VARCHAR(255) NULL ,`trip_type` VARCHAR(255) NULL  ,`service_price` VARCHAR(255) NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `traveling`.`ticketing` (`id` INT NOT NULL AUTO_INCREMENT, `client_id` INT NULL  , `is_group` VARCHAR(255) NULL , `selling_price` VARCHAR(255) NULL ,`buying_price` VARCHAR(255) NULL  ,`service_price` VARCHAR(255) NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `traveling`.`extra_service_for_reservation` (`id` INT NOT NULL AUTO_INCREMENT, `reservation_id` INT NULL  , `country` VARCHAR(255) NULL , `type` VARCHAR(255) NULL ,`trip_type` VARCHAR(255) NULL  ,`service_price` VARCHAR(255) NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `traveling`.`payment_detail_for_reservation` (`id` INT NOT NULL AUTO_INCREMENT, `reservation_id` INT NULL  , `payment_method` VARCHAR(255) NULL , `total_amount` VARCHAR(255) NULL ,`advance_amount` VARCHAR(255) NULL  ,`rest_amount` VARCHAR(255) NULL , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `traveling`.`transport_service_price_for_adult` (`id` INT NOT NULL AUTO_INCREMENT, `vip_morroco_buying_one` VARCHAR(255) NULL,`vip_morroco_selling_one` VARCHAR(255) NULL, `vip_morroco_buying_round` VARCHAR(255) NULL,`vip_morroco_selling_round` VARCHAR(255) NULL,`vip_ksa_buying_one` VARCHAR(255) NULL,`vip_ksa_selling_one` VARCHAR(255) NULL, `vip_ksa_buying_round` VARCHAR(255) NULL,`vip_ksa_selling_round` VARCHAR(255) NULL, `normal_morroco_buying_one` VARCHAR(255) NULL,`normal_morroco_selling_one` VARCHAR(255) NULL, `normal_morroco_buying_round` VARCHAR(255) NULL,`normal_morroco_selling_round` VARCHAR(255) NULL,`normal_ksa_buying_one` VARCHAR(255) NULL,`normal_ksa_selling_one` VARCHAR(255) NULL, `normal_ksa_buying_round` VARCHAR(255) NULL,`normal_ksa_selling_round` VARCHAR(255) NULL, `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `traveling`.`transport_service_price_for_child` (`id` INT NOT NULL AUTO_INCREMENT, `vip_morroco_buying_one` VARCHAR(255) NULL,`vip_morroco_selling_one` VARCHAR(255) NULL, `vip_morroco_buying_round` VARCHAR(255) NULL,`vip_morroco_selling_round` VARCHAR(255) NULL,`vip_ksa_buying_one` VARCHAR(255) NULL,`vip_ksa_selling_one` VARCHAR(255) NULL, `vip_ksa_buying_round` VARCHAR(255) NULL,`vip_ksa_selling_round` VARCHAR(255) NULL, `normal_morroco_buying_one` VARCHAR(255) NULL,`normal_morroco_selling_one` VARCHAR(255) NULL, `normal_morroco_buying_round` VARCHAR(255) NULL,`normal_morroco_selling_round` VARCHAR(255) NULL,`normal_ksa_buying_one` VARCHAR(255) NULL,`normal_ksa_selling_one` VARCHAR(255) NULL, `normal_ksa_buying_round` VARCHAR(255) NULL,`normal_ksa_selling_round` VARCHAR(255) NULL, `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `traveling`.`transport_service_price_for_infant` (`id` INT NOT NULL AUTO_INCREMENT, `vip_morroco_buying_one` VARCHAR(255) NULL,`vip_morroco_selling_one` VARCHAR(255) NULL, `vip_morroco_buying_round` VARCHAR(255) NULL,`vip_morroco_selling_round` VARCHAR(255) NULL,`vip_ksa_buying_one` VARCHAR(255) NULL,`vip_ksa_selling_one` VARCHAR(255) NULL, `vip_ksa_buying_round` VARCHAR(255) NULL,`vip_ksa_selling_round` VARCHAR(255) NULL, `normal_morroco_buying_one` VARCHAR(255) NULL,`normal_morroco_selling_one` VARCHAR(255) NULL, `normal_morroco_buying_round` VARCHAR(255) NULL,`normal_morroco_selling_round` VARCHAR(255) NULL,`normal_ksa_buying_one` VARCHAR(255) NULL,`normal_ksa_selling_one` VARCHAR(255) NULL, `normal_ksa_buying_round` VARCHAR(255) NULL,`normal_ksa_selling_round` VARCHAR(255) NULL, `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;